version: 0.2
phases:
  install:
    runtime-versions:
      java: latest
  build:
    commands:
    #Static Application Security Scan (SAST scan) using SonarCloud
      - pwd
      - mvn verify sonar:sonar -Dsonar.projectKey={UpdateValue} -Dsonar.organization={UpdateValue} -Dsonar.host.url=https://sonarcloud.io -Dsonar.token={UpdateValue} 
      - sleep 5
      
    #Quality Gates for Static Application Security Scan(SAST) using SonarCloud
      - |- 
        quality_status=$(curl -s -u {UpdateValue}: https://sonarcloud.io/api/qualitygates/project_status?projectKey={UpdateValue} | jq -r '.projectStatus.status')
        echo "SonarCloud Analysis status is $quality_status"; 
        if [ $quality_status = "ERROR" ] ; then exit 1;fi
        
    #Software Composition Analysis Scan (SCA scan) using Snyk
      - |-
          apt-get update
          apt-get -y install maven 
          SNYK_TOKEN={UpdateValue}
          export SNYK_TOKEN
          mvn snyk:test -fn 
          
    #Dynamic Application Security Scan (DAST scan) using OWASP ZAP
      - |-
        apt-get update
        apt-get -y install wget
        apt-get -y install default-jdk
        wget https://github.com/zaproxy/zaproxy/releases/download/v2.14.0/ZAP_2.14.0_Linux.tar.gz
        tar -xvf ZAP_2.14.0_Linux.tar.gz
        cd ZAP_2.14.0
        ./zap.sh -cmd -quickurl https://ginandjuice.shop/ -quickprogress -quickout ../zap_report.html
artifacts:
  files:
    - zap_report.html